### ISSUE TITLE
Identity Column value after DbSet.Add is -2147482647 or similar

### ISSUE THREAD

**Issue by J0nKn1ght** [aspnet/EntityFrameworkCore#10167]
This has been raised in other issues (e.g. #6147 and #7743), which have been closed as 'by design', but could someone explain the rational for doing this when entities are added to a DbSet?

The scenario that is causing me a problem is the same one as reported in issue #7743.  I'm developing an ASP.Net Core MVC application, and the problem is when adding a new entity instance to the database.  The model has an int identity column, and a unique index set on one of the properties. The sequence of actions is as follows:

1) An Add view is rendered with a new instance of the model, containing Id = 0.
2) The model is posted back to the controller action with Id still = 0.
3) The model is added to the DbSet using 'context.Set<T>().Add(model)', which updates the Id to -2147482647.
4) The SaveChangesAsync fails due to a duplicate key value, and this is pushed into ModelState.
5) The view is re-rendered showing the ModelState error, but now the Id control has the value -2147482647.
6) The user fixes the field which contains the duplicate key value, and re-posts the page.
7) The model is added to the DbSet again, as before.
8) The SaveChangesAsync fails, this time with the exception 'Cannot insert explicit value for identity column in table 'XXXX' when IDENTITY_INSERT is set to OFF', because it is now apparently trying to set the identity column value to -2147482647.

I don't think that this is a particularly outlandish scenario for an MVC application.  I'm using the same partial view to contain the controls for both add and edit actions, so I'd prefer not to have to put in additional code to exclude Id fields when the view is rendered for Add, rather than Edit.

What is the recommended approach to making this work?  Do we have to navigate through the object graph for the model (which in my case contains a number of nested child collections), after the add has failed, and reset any Id field with a negative value to zero?  This functionality in the new version of EF seems very clunky to me, especially as it seems to behave differently to previous versions.

I'd appreciate your advice.

Technical details
EF Core version: 2.0.0
Database Provider: Sql Server 2012 (localdb)
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 v15.4.1

**Comment by ajcvickers** [comment]
@J0nKn1ght Thanks for reporting this. To clarify something, the context instance used for the first save is different from the context instance used for the second save, correct?

**Comment by J0nKn1ght** [comment]
@ajcvickers It's a DI context registered using services.AddDbContext in the Startup.cs file, so I presume it's the same one, but I can't be sure.  Is there an easy way to log this to the output window?

**Comment by ajcvickers** [comment]
@J0nKn1ght In that setup, it's almost certainly a different instance, and that is what you want.

We will discuss this as a team, but my first thoughts are that this is a genuine problem for which I don't have an obvious solution. For now, I think you will have to either reset key values to zero before calling Add the second time, or possibly mark each key value as temporary again after calling Add (or maybe as part of a call to TrackGraph).

**Comment by J0nKn1ght** [comment]
@ajcvickers Yes, you're right - I was forgetting that the service lifetime of the DB context is scoped.

Thanks for your speedy response.  I've already added code to reset the key value to zero, which works fine, it just seems a bit counter-intuitive.

**Comment by Tarig0** [comment]
Would it be possible to have the dB context,  as part of its disposal routine,  reset temp values?

**Comment by ajcvickers** [comment]
Notes from triage: we think that it would be useful to add some better support to handle this case. For example:
* A method that detaches a graph and resets any temporary key values
  * The detaching is important because otherwise the context will be tracking entities with duplicate key values
* Another option might be to provide an easy way to clone a graph so that the actual graph sent from the client does not need to be attached--compare this to other disconnected entities scenarios
* We could do the cleanup on dispose, but in general we want to avoid dispose doing work since by far the most common scenario is that the context and entities are not touched again after dispose

**Comment by paule96** [comment]
I have the same Problem. PrimaryKey is allways  = int.MinValue + 1001

I'm realy confused. 🤨🙄😲🤪

**Comment by paule96** [comment]
Okay the EF Code have a Testcases for this [Magic number](https://github.com/aspnet/EntityFrameworkCore/search?l=C%23&q=int.MinValue+%2B1001&type=). 

Maybe we can fix this issue with a  PR.

**Comment by ajcvickers** [comment]
@paule96 Are you suggesting a PR for this feature? If so, please provide considerable details before attempting it as this is an feature for which the appropriate design/behavior is not clear. On the other hand, if you think there is a bug that needs a PR fix, then please file a new issue with full details of the bug including a runnable project/solution or complete code listing that reproduces what you are seeing.

**Comment by paule96** [comment]
I don't know if I can. I can try it. But I have found some more inconsistent behavior. In localdb the Magic Number is the result of Primarykey ID before saving and the entity state is Unchanged (!!!!). In "InMemory" Provider the PrimaryKey is the autogenerated ID befor Saving (!!!!) and the state is Added.

I think this is a provider problem if I see this. They all implement the "new" / "insert" befor saving in a different way, so you can't use the entity state to check if it the wanted action / entity ....

**Comment by paule96** [comment]
@ajcvickers git blame tell that you write the testcases for the Magic numbers. maybe you can explain why they exist?

**Comment by ajcvickers** [comment]
@paule96 Yes, I understand what these numbers are, and what this issue is about. But it seems to me that you are not really commenting on the issue described here, but more about general confusion with temp IDs and how they are used. You might be better off asking on Stack Overflow for this, but if you think there is a bug or usability issue here, then please file a new GitHub issue including full details of what you are doing and what is going wrong so that we can investigate.

**Comment by paule96** [comment]
@ajcvickers It would be nice if the numbers were documented. I think it is the same issue. The temp IDs don't make sense, in my opinion, but I think I missed only information/context about the Temp IDs. 

But the problem with the temp IDs is that whenever you want to overwrite/extend the saving methods in EF, you hit the point of real confusion.
You are right this is a usability problem, but this is what @J0nKn1ght has. Nobody think the model has a Id if it not saved. Don't put a wrong number to a model of the user from EF. 
I think it is better to handle this in entity state because of two things:
1. It removed the magic number -> because we love enums
2. EF don't set temp values to the data models, that are wrong from a business logic perspective.

@ajcvickers we can open a new issue but maybe we double this issue with this.

**Comment by ccccccmd** [comment]
I have the same Problem @paule96 @ajcvickers  

`   var  parent = await _meidaAppService.AddMedia(model);
    -- for some logic
     var sub=new ...();
     sub.parent_id = parent.Id;
     await _meidaAppService.AddMedia(sub);
`
😭 😢

**Comment by ajcvickers** [comment]
@ccccccmd If you believe there is a bug here, then can you please file a new issue including full details and a runnable project/solution that reproduces the behavior you are seeing?

**Comment by ajcvickers** [comment]
Filed #12378 which would mitigate or fix this issue.

**Comment by divega** [comment]
@ajcvickers should this marked as fixed in 3.0?

**Comment by ajcvickers** [comment]
@divega Yes, I believe so. Because the temp values are now set into the properties of the entity, so attaching it to another context instance will not result in temp values becoming real values, which is the underlying issue here. Unless I am missing something and there is more to this.

**Comment by ajcvickers** [comment]
I see--I marked it as `closed-fixed` but didn't actually close it.

**Comment by optiks** [comment]
Looking forward to removing the workaround for this. Thanks team.

**Comment by christophedemey** [comment]
I also experienced this issue, setting the Id to 0 after .Add is my workaround for now.
