### ISSUE TITLE
Add support for using response files from EF commands

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#10409]
To make something like this work:
``` cmd
dotnet ef migrations add @MyContext.ef.config
```

**Comment by bricelam** [comment]
Should be as simple as setting `command.HandleResponseFiles = true` in [src\ef\Commands\CommandBase.cs](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/ef/Commands/CommandBase.cs)

**Comment by joacar** [comment]
Hi,

Before I get started with this (I've no development experience with EF Core it self, so probably some stupid questions initially) I have some questions

1. Are there any file structure outlined
2. One file for all context or one per context
3. Where should we look for the response file
4. Default file if no context is specified

My thought is that the response file just acts as a argument container for the given context. We have `MyContext.ef.config` with the content `-p ..\A\A.csproj -o ..\B\Migrations` then executing `dotnet ef migrations add Initial -c MyContext` is `dotnet ef migrations add Initial -c MyContext -p ..\A\A.csproj -o ..\B\Migrations`.

If no context is specified when excuting the command then the default file **must** start with (or contain) the argument -c.

Additional parameters are appended to the command as expected and if a parameter is specified twice then the explicit parameter takes precedence over the parameter defined in the file.

- [ ] Architecture
- [ ] Tests
- [ ] Code
- [ ] Document

**Comment by bricelam** [comment]
Response files are a general feature of the command-line argument parser. We'd simply turn it on for the `dotnet ef` commands.

The feature lets you read command-line arguments from a file. For example, if `ECHO` supported it (it doesn't), you could to this to print out the contents of `message.txt`.

``` cmd
ECHO @message.txt
```

`dotnet ef` would never automatically load one of these files. You'd always have to specify it. To use this feature as you originally requested it, you'd have to put each context in its own file.

**Comment by jsacapdev** [comment]
@bricelam this is a feature that i would find useful and so i have had a go with the changes and it works as you explained. do you have any guidance on unit testing?

For me I created a project and at the command line ran something like dotnet ./dotnet-ef.dll migrations list @BloggingContext.ef.config. Because the entry point is calling the command line, I am unsure on your preferred approach as to how to achieve this in an automated way (is there an expectation for automated testing at the command line level)? Or is it sufficient for the entry point to just test CommandLineApplication::ExpandResponseFiles().

If you do have any further thoughts and/or guidance on how to approach the unit testing that would be appreciated.

**Comment by bricelam** [comment]
I think we can sort out adding automated tests as part of #9111. If you've manually verified it works, go ahead and submit the PR.

**Comment by joacar** [comment]
For those waiting and want a temporary solution here is what I've used mean while

## Add-Migration
```bat
@echo off
set /p args=<%2

pushd %~dp0src\WebApp

echo on
dotnet ef migrations add %1 %2

@echo off
popd %~dp0
```

Similarly for `Remove-Migration` and `Update-Database`.
