### ISSUE TITLE
Query: Distinct on non-materialized QSRE could give incorrect result

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10433]
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs#L2726-L2738

Generates
```SQL
SELECT [t].[HasSoulPatch]
FROM (
    SELECT DISTINCT [ig].*
    FROM [Gears] AS [ig]
    WHERE [ig].[Discriminator] IN (N'Officer', N'Gear')
) AS [t]
```
This could generate incorrect results if `Gears` table has some non-mapped columns. So even though expectation is distinct records there could be duplicates.
We should probably expand * projection to full list of mapped properties here to get closer to linq behavior.

@anpete @divega @ajcvickers - thoughts?

**Comment by divega** [comment]
@smitpatel explained that he was removing the star projection from cases like this, but it became apparent that for DISTINCT we should have the full list of columns (as opposed to just what is being projected in the outer projection). 

Personally, I would not expect non-mapped columns to have an influence in the results.

There is however an optimization when the root is a scan over an entity type (with optional filters and sorting): just eliminate the whole DISTINCT because we know that we will be getting a unique PK value per row (see https://github.com/aspnet/EntityFrameworkCore/issues/8643).

**Comment by ajcvickers** [comment]
Assigning to @anpete as part of #9290.

**Comment by smitpatel** [comment]
Generated SQL in new pipeline
```SQL
SELECT [t].[HasSoulPatch]
FROM (
    SELECT DISTINCT [g].[Nickname], [g].[SquadId], [g].[AssignedCityName], [g].[CityOrBirthName], [g].[Discriminator], [g].[FullName], [g].[HasSoulPatch], [g].[LeaderNickname], [g].[LeaderSquadId], [g].[Rank]
    FROM [Gears] AS [g]
    WHERE [g].[Discriminator] IN (N'Gear', N'Officer')
) AS [t]
```
