### ISSUE TITLE
Migrations: Changing delete behavior from restrict -> ClientSetNull causes FK to be modified

### ISSUE THREAD

**Issue by Tarig0** [aspnet/EntityFrameworkCore#10543]
Describe what is not working as expected.

When changing the delete behavior for a relationship from Restrict -> ClientSetNull; The migration engine will generate a unneeded drop and create.

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: Visual Studio 2017 15.4

**Comment by bricelam** [comment]
Interesting. Because of the mapping from `DeleteBehavior` to `ReferentialAction`, we should treat `DeleteBehavior.ClientSetNull` and `DeleteBehavior.Restrict` the same when diffing.

DeleteBehavior | ReferentialAction
-------------- | -----------------
Cascade        | Cascade
SetNull        | SetNull
ClientSetNull  | Restrict
Restrict       | Restrict
