### ISSUE TITLE
Question:Design Core(Rev Eng):Context Class: How to add namespace while generating Context class 

### ISSUE THREAD

**Issue by archanasoni** [aspnet/EntityFrameworkCore#10629]
Hi,
We are working to have Design Core support for our IBM EntityFramework Core provider.
Currently our dev infra is based on Core 2.0.
When we generate model, context class contains default namespace. We require to add here IBM EntityFramework Core provider namespace as well. 
To Do this we had to extend CSharpDbContextGenerator class which is part of Microsoft.EntityFrameworkcore.Design package. 
Just for this particular requirement we have to target another package, which we are not willing to do due to some reasons.
Is there any way to achieve the above requirement by targeting Microsoft.EntityFrameworkcore.Relational pkg ?
For example  IScaffoldingProviderCodeGenerator interface provides us method, through which, we can generate UseDb2.. method code.

Regards,
Archana

**Comment by bricelam** [comment]
What generated code is requiring the namespace?

**Comment by archanasoni** [comment]
@bricelam to use method UseDb2(...) in OnConfiguring(..) we add namespaces, for example:
using IBM.EntityFrameworkCore;
using IBM.EntityFrameworkCore.Storage.Internal;
....
....
 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseDb2(ConnectionString, p => { p.SetServerInfo(IBMDBServerType.OS390); p.UseRowNumberForPaging(); });
        }
...
...

**Comment by ErikEJ** [comment]
I just use the Microsoft.EntityFrameworkCore namespace for extension methods. (Ie UseDb2 and SetServerInfo)

**Comment by ajcvickers** [comment]
@archanasoni As @ErikEJ says, these extension methods should live in "Microsoft.EntityFrameworkCore". Even with improvements in tooling it is still hard for some people to discover where extension methods live, so we take the approach of putting them in a common namespace that it likely to already be included. We do the same for the providers we own and we have also given this guidance to the authors of other providers.

Also, I notice that the code example has a using for an "internal" namespace. This seems like a very bad idea, since code in internal namespaces changes between releases, so there should be nothing directing an application to use internal namespaces. If applications chose to use them at there own risk, then that should be an explicit choice, and not something that happens automatically when reverse engineering.

All that being said, I see you are using an enum type in the generated code. I can see that maybe it would be valid to have this in your own namespace. For now I would suggest you fully qualify it when scaffolding.

**Comment by ajcvickers** [comment]
@archanasoni Also, please make sure your provider is not making use of any code in EF internal namespaces. It is very bad for providers to use internal code since it will cause a provider written for one version of EF to fail when used with a new version of EF, which, outside of major version changes, we really want to avoid.

**Comment by ajcvickers** [comment]
Notes from triage: Currently the reverse engineering infrastructure for 2.1 does not support more than UseXxx with a connection string. It should be enhanced to also support other builder calls, either on optionsBuilder or the provider-specific builder. However, this might not get done for 2.1, so in that case a provider should be able to still use the 2.0 APIs with the understanding the it will only support C# code gen, not F# or VB. Assigning to @bricelam in 2.1 to determine whether or not we need to do anything in 2.1.

**Comment by bricelam** [comment]
@archanasoni Like #10808, are you open to making `SetServerInfo` and `UseRowNumberForPaging` return the builder?

For the updated 2.1 interfaces, I'll enable generating code like this:
``` csharp
.UseDb2(ConnectionString, p => p.SetServerInfo(IBMDBServerType.OS390).UseRowNumberForPaging())
```
