### ISSUE TITLE
Add developmentDependency=true to EFCore.Design

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#11506]
This dependency typically shouldn't be published with the application.

**Comment by bricelam** [comment]
Re-opening to add a breaking change note

**Comment by bricelam** [comment]
Breaking change note added in https://github.com/aspnet/EntityFramework.Docs/pull/1536

**Comment by AraHaan** [comment]
For some reason, this package seems to be copied (again the 7.0.0-* release of the package) to my project outputs. Should this still be marked as an development dependency?

**Comment by ErikEJ** [comment]
@AraHaan please share your .csproj

**Comment by AraHaan** [comment]
It turns out it was due to me manually typing the ProjectReference to a single like and ommitted the ``PrivateAssets`` and ``IncludeAssets`` again 😔. I wonder why MSBuild does not default ``PrivateAssets`` on package references to ``all`` and the ``IncludeAssets`` to ``runtime; build; native; contentfiles; analyzers``.
