### ISSUE TITLE
IncludeExpressionNode and ThenIncludeExpressionNode throw different exception types

### ISSUE THREAD

**Issue by tuespetre** [aspnet/EntityFrameworkCore#11598]
The `IncludeExpressionNode` has an additional (unnecessary?) pre-check that throws `InvalidOperationException`, whereas the `ThenIncludeExpressionNode` does not have that pre-check and instead lets `GetComplexPropertyAccess()` throw its `ArgumentException`. I think the two need to be made consistent. There are a couple of tests that would need to be updated as well.

https://github.com/aspnet/EntityFrameworkCore/blob/0e1d2ca3d7b4dc49b77368ede5ccb8b26a4fa1f3/src/EFCore/Query/ResultOperators/Internal/IncludeExpressionNode.cs#L46-L68

https://github.com/aspnet/EntityFrameworkCore/blob/0e1d2ca3d7b4dc49b77368ede5ccb8b26a4fa1f3/src/EFCore/Query/ResultOperators/Internal/ThenIncludeExpressionNode.cs#L46-L58

**Comment by ilmax** [comment]
@tuespetre What about adding a `TryGetComplexPropertyAccess` that returns false instead of throwing an exception to avoid duplicating the same checks `GetComplexPropertyAccess` is already doing, just throw a more useful exception message if the `TryGetComplexPropertyAccess` returns false?
This would also result in make `GetComplexPropertyAccess` to call `TryGetComplexPropertyAccess` and throw an exception if it returns false.
