### ISSUE TITLE
Query: misleading exception message when we are expecting non-null value but getting null instead

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#12698]
Scenario can be found here:

https://github.com/aspnet/EntityFrameworkCore/issues/12663

Exception is:

An exception occurred in the database while iterating the results of a query for context type 'recordingsContext'.
System.InvalidOperationException: Nullable object must have a value.

Confusing part is that the exception doesn't happen in the database, but rather on the client.
Also, it's not quite obvious what's happening here - i.e. we are expecting a non-nullable element (e.g. int) but got a null instead.

**Comment by divega** [comment]
@divega needs to come up with proposal.

**Comment by divega** [comment]
Actually the message needs to stay generic because it is used to wrap any exceptions that occur during MoveNext. But we can certainly tweak it to make it more accurate. My proposal is to just remove the word "database" to make it less misleading:

```
An exception occurred while iterating over the results of a query for context type '{contextType}'.{newline}{error}"
```

There is an argument for trying to make the exception more useful, e.g. including the name of the field that causes the failure in the "inner" exception, but I suspect there are potential performance and security implications in that, so bring it back to triage for discussion.
