### ISSUE TITLE
Query: Avoid calling ValueBuffer.Equals()

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#13085]
Only values should be compared--not entire buffers. Making this method throw shows a few test failures.

Functional Tests | Failures
--- | ---
InMemory | 4
Sqlite | 6
SqlServer | 8

**Comment by smitpatel** [comment]
We run into using `Equals` method due to client side implementation.
For query like below, (untested)
```C#
context.Blogs.Where(b => ClientMethod(b.Id)).Distinct().Select(b => b.Value).ToList();
```
Here, we have a client Where which causes us to evaluate Distinct on client. But at the same time we are not projecting out the entity, so we use ValueBuffer rather than entity. Doing operations like Distinct/Contains etc on enumerable causes call to Equals method. We should be materializing entity for such cases but currently materialization is separated from client eval so we don't have a way to fix it.
