### ISSUE TITLE
Inconsistency in Lazy Loading Behavior

### ISSUE THREAD

**Issue by JoesGab** [aspnet/EntityFrameworkCore#13122]
I noticed some inconsistencies in the loading behavior of navigation proxies. I'm not entirely sure what the expected behavior should really be, but the Gist from the next section contains my point of view in a few xUnit tests.

#### Case A
An entity **without** eager loaded (null) navigation property lazy loads the navigation property after changing the corresponding Id. => Works as expected

#### Case B
An entity **without** eager loaded (non-null) navigation property lazy loads the navigation property after changing the corresponding Id. => Works as expected

#### Case C
An entity with eager loaded (null) navigation property lazy loads the navigation property after changing the corresponding Id. => Does **not** work as expected

#### Case D
An entity with eager loaded (non-null) navigation property lazy loads the navigation property after changing the corresponding Id. => Works as expected

### Steps to reproduce
https://gist.github.com/JoesGab/886929c65c119ecceddef9ff6f37d1ab

### Further technical details
EF Core version: 2.1.2
Database Provider: (e.g. Microsoft.EntityFrameworkCore.InMemory)
Operating system: Win10 Enterprise
IDE: (e.g. Visual Studio 2017 15.8.1)

**Comment by ajcvickers** [comment]
Note for triage: there are two issues here:
* First, something needs to detect that the FK value has changed. By design, this would require DetectChanges to be called, but it may be pragmatic to put a localized check for just the FK here
* Second, if the FK changes, but the navigation remains null after the changes, then the relationship is still flagged as "loaded". Explicitly setting clearing the flag results in lazy-loading happening.

**Comment by ajcvickers** [comment]
Fixing the issue for 2.2 where a navigation already null does not have IsLoaded reset when the underlying FK changes. However, not implementing this in absence of DetectChanges because it would be better done as part of a wider change to do local DetectChanges as tracked by #13552
