### ISSUE TITLE
Use a CodeFragment for CoreTypeMapping.FindCodeLiteral()

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#13414]
Instead of passing in `language` and returning a `string`, we moved to using strongly-typed, language-agnostic types for design time. (`MethodCallCodeFragment` and `NestedClosureCodeFragment`) This allows providers to be independent and language packages to be self-contained. The user doesn't have to jump through hoops because a provider doesn't know how to generate for their particular language.

We should consider doing the same for `CoreTypeMapping.FindCodeLiteral()`.

**Comment by ajcvickers** [comment]
@bricelam I investigated this some, but I think it should wait for 3.0 because:
* The existing fragments are in the Design assembly, but the type mapper doesn't have access to that.
* There are several variations of fragment needed--for example, `null`, `new Foo(args)`, `Foo.Create<T>(args)`, `(Foo)new X().Read(args)`. It's not clear how these variations should be factored, and the more different things we need, the more it looks like expression trees.

Also, there is no good place to put the helper factory method that we talked about that isn't specific to a particular provider but references NTS.

Propose that we do the simple thing for 2.2, and revisit in 3.0.
