### ISSUE TITLE
Memory Leak with RelationalConnection

### ISSUE THREAD

**Issue by JakobFerdinand** [aspnet/EntityFrameworkCore#13888]
Any query (`IBufferable`) gets registered at the `RelationalConnection` which is shared between all instances of `DbContext` but they are never unregistered, so a memory leak happens.

In [QueryingEnumerable.cs](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs):
Line 109: [_relationalQueryContext.Connection.RegisterBufferable(this);](https://github.com/aspnet/EntityFrameworkCore/blob/1032daf61fae290f9139d07fb9f6c2b847a48d60/src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs#L109)

![inkedmemorytest20181030](https://user-images.githubusercontent.com/16666458/47999824-fbc5dd00-e103-11e8-9e57-0bcedbb23bb2.jpg)

### Further technical details
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 18.03
IDE: Visual Studio 2017 15.8.9

**Comment by ajcvickers** [comment]
@smitpatel to follow up

**Comment by smitpatel** [comment]
> RelationalConnection which is shared between all instances of DbContext

`IRelationalConnection` is scoped service just like `DbContext`. Each DbContext instance has its own copy of `RelationalConnection`. During the lifetime of `DbContext`, `RelationalConnection` remembers the all the queries used with the context instance. We could possibly unregister it after the query has fully enumerated (to align better with "activeQueries" since query is not longer active after it finished enumerating). But this is not a memory leak unless you are using same context for long time rather than unit of work.

**Comment by smitpatel** [comment]
Merged via 4236dfd7f2789782cbba26bf0af15b04dfaf2a0c
