### ISSUE TITLE
string.StartsWith translator LEFT(LEN()) problem

### ISSUE THREAD

**Issue by nikodz** [aspnet/EntityFrameworkCore#14657]
Hello everyone,

As it's written in [SqlServerStartsWithOptimizedTranslator.cs](/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStartsWithOptimizedTranslator.cs) `string.StartsWith` is translated as two expression, `Like` and `LEFT(LEN())`. As I have found, a reason of making `LEFT(LEN())` is optimization.
I took executed script from my application and try to run first as it was executed and then without second part of expression. It seems that in my case, `LEFT(LEN())` is slowing the execution.

Is it possible to skip `LEFT(LEN())` expression in any way?

**Comment by roji** [comment]
@nikodz the `LIKE` part of the expression is meant to be an efficient (index-powered) first test to weed out most non-matching cases. However, even if the `LIKE` is true, the `LEFT(LEN())` part is still required to be sure, since the LIKE expression is inaccurate if it contains any wildcards. So simply omitting the `LEFT(LEN())` could yield incorrect results, which is not a good thing.

However, looking at the current SQL Server implementation, it seems that the `LEFT(LEN())` check is done even when the pattern is constant. In other words, it seems like we did not implement https://github.com/aspnet/EntityFrameworkCore/issues/474#issuecomment-278199281 - this would make use check for constant patterns which don't contain wildcards, and skip the `LEFT(LEN())` part for them. In fact, even for constant expressions with wildcards, we could simply escape them client-side. Note a similar recent perf complaint here: https://github.com/aspnet/EntityFrameworkCore/issues/11881#issuecomment-427230022.

/cc @maumar @divega

**Comment by roji** [comment]
As a workaround, it's possible to simply use `LIKE` directly via `EF.Functions.Like()` (see [these docs](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#effunctionslike)).

Otherwise we'll try to optimize the constant pattern case for 3.0, after the query pipeline work is finished.

**Comment by roji** [comment]
Merged PR into smit/query, closing.
