### ISSUE TITLE
Mitigate breaking changes in Migrations

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#14867]
It seems like there are a few places in Migrations that we're always breaking or introducing new overloads (e.g. around column facets) we should investigate whether it's worthwhile to introduce some parameter objects in 3.0.

**Comment by bricelam** [comment]
Candidate methods:
* MigrationsSqlGenerator
  * SequenceOptions
  * ColumnDefinition
  * GetColumnType

**Comment by bricelam** [comment]
Looks like the implementation of #8764 will be affected by this work, so I'll tackle both at the same time.

**Comment by roji** [comment]
While porting EFCore.PG to preview4 I ran into a snag: now that a ColumnOperation is being passed around instead of a bunch of parameters, it becomes difficult for the MigrationSqlGenerator to, say, change a type. For example, in PostgreSQL if the user specifies a value generation of "serial" on an "int", the generator modifies the actual type generated to be "serial".

This used to be trivial (just pass a different type), but now I'm forced to mutate `ColumnOperation.ColumnType`, which seems wrong - but maybe it isn't. I could clone it with a new type, but there's no infrastructure around cloning, and there are several types of ColumnOperation so this could get heavy.

For preview4 I'll just mutate `ColumnOperation.ColumnType` but it's worth thinking about.

**Comment by bricelam** [comment]
@roji I had a similar delima on SQL Server where DefaultValue, DefaultValueSql, and SqlServerValueGenerationStrategy can't be specified during ALTER column:

https://github.com/aspnet/EntityFrameworkCore/blob/2cce9c524f66dc183661cde92348e48501c1cc6e/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L301-L318
