### ISSUE TITLE
Use KeyAtrribute for scaffolding to support OData

### ISSUE THREAD

**Issue by cilerler** [aspnet/EntityFrameworkCore#15677]
OData requires `[Key]` attribute for entities where the primary key property name is not `Id` _(it can't use `.HasKey()` info in FluentAPI)_

Please allow scaffolding to generate Key Attributes if the column is name is not `Id` or the key is different than the `Id` property.

**Comment by ajcvickers** [comment]
Notes from triage: the discussion in #11003 on how `[Key]` is used by OData indicates that it can be useful to have `[Key]` on properties _even if doing so is not sufficient for EF Core mapping_. Another example of this is data binding where properties attributed with `[Key]` may be hidden by default.

A couple of concrete things that come out of this:
* When working on #11003 we should consider the benefits of using `[Key]` with something else that specifies ordering, as opposed to a new attribute that specifies both. However, the new attribute approach is likely to be cleaner, so this is not a decision that we should do one verses the other, just a note to consider both.
* When scaffolding from a database, we should consider putting `[Key]` on the properties (in addition to scaffolding fluent API) either:
  * Whenever data annotations have been requested
  * Or as part of #9580, since while key is not a validation attribute _per se_ it can be useful in the same way

Note that we should also make sure that we don't log a warning  the properties have `[Key]` but are correctly configured in the fluent API anyway.

**Comment by ErikEJ** [comment]
This would be really nice to have, also for EF Core Power Tools - is this up for grabs, of should I overide the service as suggested here in the meantime:

https://github.com/aspnet/EntityFrameworkCore/issues/11003#issuecomment-491106261

**Comment by divega** [comment]
@ErikEJ I think it is ok if you want to go ahead with a PR. @ajcvickers, any concerns?

**Comment by ErikEJ** [comment]
As I understand this, the goal is to always scaffold Key attribute for all involved properties when DataAnnotations are requested. Or always?

**Comment by divega** [comment]
My understanding is that KeyAtrribute being used will still depend on whether you ask for DataAnnotations to be used, but no longer on whether the key is composite. And in the latter case we will still generate the HasKey method so that the key mapping works for EF Core (because we need the key member ordering information).

The relevant comment is https://github.com/aspnet/EntityFrameworkCore/issues/11003#issuecomment-491078121.

**Comment by ajcvickers** [comment]
@ErikEJ Agree with Diego's last comment. Also, almost any issue that isn't closed is something that we would take a PR for--it doesn't have to have `good-first-issue` on it, which is what `up-for-grabs` has now become.
