### ISSUE TITLE
QueryRewrite: add support for FromSql

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#15704]
Issue for tracking purposes - when FromSql works, make sure to enable skipped tests.

**Comment by roji** [comment]
Note from discussion: in the old pipeline it was possible have `FromSql()` anywhere in the query - ordering was ignored (e.g. a predicate specified before the `FromSql()` was rendered after it in the SQL query). We have decided to disallow this and make the following changes:
* Change FromSqlRaw() and FromSqlInterpolated() to be extension methods on DbSet instead of on IQueryable
* Leave the obsolete FromSql() on IQueryable so that users have a chance to see the obsoletion message. However, a runtime check will still throw if FromSql() is specified on a non-DbSet.

**Comment by roji** [comment]
Note: splitting out parameter support to #15750 as discussed with @smitpatel

**Comment by divega** [comment]
@roji reopening so that we can remember to document the additional breaking changes for preview 6.

**Comment by roji** [comment]
Oops, forgot about that - will submit a doc PR soon.
