### ISSUE TITLE
QueryRewrite: parameter support for FromSql()

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#15750]
Basic FromSql() support is implemented in #15704, but parameter support was left for later to review how to best do this.

**Comment by smitpatel** [comment]
Also 
- FromSql with stored proc
  - Remapping the columns

**Comment by smitpatel** [comment]
Implementation notes:
- FromSql args are always going to be of type `object[]`. It is parameter for implicit query compilation and constant for compiled queries.
- Most of the processing would remain similar to what we had in DefaultQuerySqlGen. NewArrayInit is not possible anymore so that piece of code can be removed.
- object[] can contain any type of value or DbParameters. This require us to have TypeMappingSource available during SqlGen.
- Add IRelationalTypeMappingSource dependency in QuerySqlGenerator. (also change to Singleton service).

That concludes parameter support.

For sproc, we need to remove wrapping layer,
- After we generate shaper and before we compile into QueryingEnumerable, check for possible composition after FromSql. If none then lift the FromSqlExpression out. Have a way to generate command for that in QuerySqlGen. Generate different QueryingEnumerable and mutate the shaper to generate `Func<QueryContext, DbDataReader, int[], TResult>` Here `int[]` would be remapping map which needs to go inside shaper whenever we are accessing particular ordinal. Value of such map would be computed after we open the reader and stored inside enumerator.

@roji - Do you want to work on this? (Priority would be after entity equality)

**Comment by roji** [comment]
@smitpatel sure - am much less clear on the shaper side of things but will ask you for help as needed.
