### ISSUE TITLE
Translation of Lambda in SqlTranslator throws exception

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#16597]
The following query fails:

```c#
var _ = ctx.SomeEntities
    .Where(e => e.SomeText.Any(c => c == 'a'))
    .ToList();
```

Exception:
```
System.InvalidOperationException : When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.ParameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit children of this type.
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](T node, String callerName)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitParameters(ExpressionVisitor visitor, IParameterProvider nodes, String callerName)
   at System.Linq.Expressions.ExpressionVisitor.VisitParameters(IParameterProvider nodes, String callerName)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in /home/roji/projects/EFCore/src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs:line 356
```

This happens because the inner lambda's ParameterExpression gets translated to an SqlParameterExpression, but ExpressionVisitor.VisitLambda validates that ParameterExpressions remain ParameterExpressions.

@smitpatel, does this ring a bell, do we already have an issue tracking this? We probably need an SqlLambdaExpression here to hold these SqlParameterExpressions; these lambdas won't need to be compiled so anything should be OK (although client evaluation in top-level select?).

(the actual problematic scenario I had was while implementing some operations over PostgreSQL arrays)

**Comment by smitpatel** [comment]
Not an existing issue. For relational Any is always defined on Queryable which translate to existing so code path never reach here. There is no SqlLambda (there is not lambda printed in SQL tree). What is the translation you are expecting to server side for this scenario? You may need to intercept early and apply translation. Ideally, VisitLambda in sql translator will return null. We cannot represent `c => c == 'a'` in SQL (at least in relational)

**Comment by roji** [comment]
`e.SomeText.Any(c => c == 'a')` can be rewritten as `e.SomeText.Contains('a')` which we already translate (with `CHARINDEX` on SqlServer). Another more interesting example for PostgreSQL is `.Where(e => new[] { "a%", "b%", "c%" }.Any(a => EF.Functions.Like(e.SomeText, a))`, which can be translated as `WHERE e.SomeText LIKE ANY ('a%', 'b%', 'c%')` ([see this test](https://github.com/roji/Npgsql.EntityFrameworkCore.PostgreSQL/blob/145753428f7374a50b1912c7e0881a5993659959/test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs#L265)). Unlike the former example, which can simply be rewritten in the optimization phase, the latter cannot. Note that the latter translation existed in the old pipeline and worked well.

The point here is to be able to identify specific constructs with Any (or any operator) which can be rewritten and translated - this currently can't be done with a regular method translator because of the Parameter/SqlParameter mismatch in VisitLambda. [This can be worked around by pattern matching in SqlTranslatingEV](https://github.com/roji/Npgsql.EntityFrameworkCore.PostgreSQL/blob/145753428f7374a50b1912c7e0881a5993659959/src/EFCore.PG/Query/Pipeline/NpgsqlSqlTranslatingExpressionVisitor.cs#L74) (so this isn't blocking/critical), but seems like it should be possible in a regular method translator instead. If you feel that this isn't necessary and the workaround is sufficient, we can close.

**Comment by roji** [comment]
Note, by the way, that [parameterless Any can be already be easily translated in a regular method translator](https://github.com/roji/Npgsql.EntityFrameworkCore.PostgreSQL/blob/145753428f7374a50b1912c7e0881a5993659959/src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayMethodTranslator.cs#L59).

**Comment by smitpatel** [comment]
After thinking about this in details, following are my conclusions
- Translation of Any/All goes into 2 different branches
    - Any/All on IQueryable gives us chance to convert the predicate to Where on Queryable. That is how we translate currently.
    - In all other case of Any/All, we cannot convert to where. `c.SomeText.Any(c => c == 'a')` is equivalent of `c.SomeText.Where(c => c == 'a').Any()`. Sadly, we don't have any translation of such Where predicate (be it on some column/constant/parameter of array/string). Hence in this branch (when Any/All is not on IQueryable, what we can translate from predicate is very limited.
- Focusing on the 2nd branch described above, We can translate `Any(c => c == 'a')` & `All(c => c != 'a')` using InExpression. We do optimization to convert them to Contains. Since for those particular cases, they are equivalent. Can we translate more structures of predicate? May be but we haven't got feedback from customers and we haven't investigated ourselves (except for following).
- `new[] { "a%", "b%", "c%" }.Any(a => EF.Functions.Like(e.SomeText, a))` falls into same category of second branch. A particular structure of predicate npgsql can translate using `LIKE ANY`

Now going into the side of implementation of such translation
- There is no translation of lambda on server side. There is no SQL equivalent of `c => c =='a'`
-  `IMethodCallTranslator` are method call translators which can work piece-wise. Translate instance & all arguments first and then invoke the translation with translated pieces.
- This works for nested but still independent method calls. E.g. `stringColumn.Substring(stringColumn.IndexOf("a"))` can be translated since IndexOf can be translated without knowing about outer tree.
- Due to piece-wise behavior, such method call translators cannot have lambda arguments. Since lambda attaches outer closure. Each subtree is no longer independent. (Therefore lambda cannot be translated on its own either).
- For the particular case of `LIKE ANY`, the client side tree utilizes 2 different functions and a lambda and it would work only when the lambda is very specific (function call to LIKE) and you also have to look at both together. So at bare minimum you have to pattern match the tree to identify such structure. Current MethodCallTranslators are not designed to identify complex structure. Their simplicity of piece-wise makes it easy to implement. So no, translation of LIKE ANY cannot fit in IMethodCallTranslator directly. It's wrong instrument to use for such purpose.

Available options are
- Add altogether a different instrument to translate such method calls (possibly fails in value vs cost)
- Pattern match in SqlTranslator directly (like how it is done right now)
- Since pattern matching has to be done in some place anyway, if the point is to use existing IMethodCallTranslator somehow, then `LIKE ANY` while expressed on client side with Any/Like, from SQL perspective it is one function, `LikeAny(string matchExpression, string[] patterns)` If you introduce such method call on client side after pattern matching, you can pretty much use existing IMethodCallTranslator infra.


So to answer the questions above,
>  Unlike the former example, which can simply be rewritten in the optimization phase, the latter cannot.

It can if you introduce a different method call which is equivalent of server side function and which can work piece-wise

> this currently can't be done with a regular method translator because of the Parameter/SqlParameter mismatch in VisitLambda

Issue isn't VisitLambda. Issue is each subtree supposed to be translated independently. (which is true for everything inside SqlTranslator), LambdaExpression violates that due to closure access.

> seems like it should be possible in a regular method translator instead.

I provided a way how to do it in IMethodCallTranslator above which can also be done in optimization phase like how we generate Contains.

> parameterless Any can be already be easily translated in a regular method translator

Due to lack of lambda arguments. Anything which can be translated piece-wise can be translated in SqlTranslator. (Except for things which cannot be represented in SQL due to type like anonymous type).

I believe, above would answer everything.
The only pending work on EF Core side is to return null for VisitLambda in SqlTranslator (for relational/cosmos both)

**Comment by smitpatel** [comment]
Re-opening for visibility in triage.

**Comment by roji** [comment]
@smitpatel the explanation above makes a lot of sense to me, thanks for taking the time to do the write-up. Agreed that complex translation does not belong in IMethodCallTranslator, and therefore there's no reason to translate non-toplevel lambdas.

Note: NavigationExpander rewrites Any(x) to Where(x).Any(). The rewriting itself seems OK, but it's surprising that it's done in navigation (and feels like it could accidentally disappear one day)... Should we maybe move this to a more generic NormalizingEV that runs early in the optimization pipeline, and which would potentially do other things (e.g. #15931). If this makes sense to you, I can open a cleanup issue for the backlog.

**Comment by smitpatel** [comment]
> NavigationExpander rewrites Any(x) to Where(x).Any(). The rewriting itself seems OK, but it's surprising that it's done in navigation (and feels like it could accidentally disappear one day)

It is just side effect of current implementation. Not a requirement. Translation pipeline handles both cases properly already. We don't need any normalization.
