### ISSUE TITLE
Tagged or named queries

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#1664]
We could add an extension method for IQueryable<T> that allows a tag (or name, or arbitrary annotation) to be associated with the query. On query execution we can then flow that piece of information to lower levels, e.g. either our logging code or the provider could include that information in the generated log messages or even in the generated query (e.g. in the SQL as a comment) to facilitate correlating the target query with the origin in the source code.

A general purpose annotation mechanism could have other uses, e.g. provider could define their own well-know annotations to be used for such things are query hints. 

It is not clear if these tags could be leveraged by query caching.

**Comment by KLuuKer** [comment]
Yes 1000x YES!

Please add some sort of tagging all the way to the actual sql query (using comments as you said).

Maybe also add some kind of tag\hint\comment per "expandable" subquery.
Because I am currently looking in the sql query store and am thinking where the hell is this thing coming from? Queries ranging from a couple of lines all the way to "there be dragons here".... (big ecommerce app)

We are using LinqKit to create reusable subqueries and being able to identity those subqueries would be a helpful addition, so I can focus on the bigger picture of the query and not keep thinking "what subquery was thing again?" when analyzing why our perf is so bad.

**Comment by divega** [comment]
@ajcvickers @anpete I assume the right milestone for this would be 2.2, right?

**Comment by ajcvickers** [comment]
Yes

**Comment by jzabroski** [comment]
@divega  This Tags concept is a great idea. One thing possibly missing from EFCore is a QueryListener interception context separate from and dual to CommandListener. This would be the ideal code path to inject [CallerMemberName]

agree?

not a blocking issue, just opening up the conversation if there can be a generic place for all DbSet<T> chains to log their (transitive) caller. Simple test scenario is projection into a DTO.

I agree Tags could be used for caching, perhaps a special StrongTag.

Documentation on Tagging should also remind users that overly dynamic Tags will bloat query plan caches. Perhaps EF should leverage its caching infrastructure to admit Log.Warn warnings for when the same query has multiple tags, or two different queries have the same tag collection. Tag collections should therefore be a POS - partially ordered set.

**Comment by roji** [comment]
Add `provider-fyi`, as not doing this causes ComplianceTestBase to fail...
