### ISSUE TITLE
Stop using Debug.Assert

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#17204]
Because the current generation of test runners don't handle it well--they seem to just crash.

Instead we can have our own debug-only pattern that just throws and exception.

**Comment by roji** [comment]
Dug a little bit into this.

Debug.Assert used to be customizable via TraceListeners, which allow you define the behavior for failures. This apparently didn't work in Core, but is being brought back in 3.0 (see https://github.com/dotnet/coreclr/issues/22569).

Bottom line: IMHO we should continue using Debug.Assert, but if we don't like the default failfast behavior we can set it up to throw an exception instead.

**Comment by ajcvickers** [comment]
Looked into the link @roji posted, but it still seems easier and more reliable to just not use Debug.Assert rather than to try to make sure `Trace.Listeners` is set correctly for every test.

**Comment by roji** [comment]
I don't really see any drawback to simply globally configuring the TraceListeners in our tests (which seems to be the standard .NET way of asserting stuff), rather than changing our entire codebase to change from Debug.Assert to something else. But I also don't have strong feelings about this, and can do whatever we prefer.
