### ISSUE TITLE
Added owner referencing detached weak owned entity can throw when detached

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#17456]
Repro code is below:

Note that using `context.Add(owner);` doesn't have this problem because it doesn't leave the owned entity in a detached state.

```C#
public class Owner1
{
    public int Id { get; set; }
    public Owned Owned { get; set; }
}

public class Owner2
{
    public int Id { get; set; }
    public Owned Owned { get; set; }
}

public class Owned
{
}

public class BloggingContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlite("DataSource=Test.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Owner1>().OwnsOne(e => e.Owned);
        modelBuilder.Entity<Owner2>().OwnsOne(e => e.Owned);
    }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var owner = new Owner1 { Owned = new Owned() };
            context.Entry(owner).State = EntityState.Added;
            context.Entry(owner).State = EntityState.Detached;
        }
    }
}
```

Exception:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'derivedType')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.EntityTypeExtensions.IsAssignableFrom(IEntityType entityType, IEntityType derivedType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c__DisplayClass67_1.<StopTracking>b__0(INavigation n)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StopTracking(InternalEntityEntry entry, EntityState oldState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState
, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptCha
nges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.set_State(EntityState value)
   at Program.Main() in C:\Stuff\ThreeOhP7P\ThreeOhP7P\Program.cs:line 254
   at Program.<Main>()
```

**Comment by ArrowRaider** [comment]
The following is based off debugging the v3.0.0 tag:

The problem is caused by EFCore\ChangeTracking\Internal\StateManager.cs
In method _RecordReferencedUntrackedEntity_, "owned" types are added to __referencedUntrackedEntities_
In method _StopTracking_, __referencedUntrackedEntities_ is iterated and this value gets assigned null:
`untrackedEntityType = _model.FindRuntimeEntityType(keyValuePair.Key.GetType());`
It is null because __entityTypes_ in EFCore\Metadata\Internal\Model.cs doesn't contain owned types.

A possible solution might be to insert this line in _RecordReferencedUntrackedEntity_:
`if (navigation.ForeignKey.IsOwnership) return;`
Above line:
`if (!_referencedUntrackedEntities.TryGetValue(referencedEntity, out var danglers))`

**Comment by AndriySvyryd** [comment]
@ArrowRaider We would need to add more tests to cover related scenarios. Untracked owned entities shouldn't be just skipped, since then it might get fixed up in an unexpected way later. We should also not try to guess the entity type based on the current navigation, as there could be more than one navigation of the same .NET Framework type. Instead `_referencedUntrackedEntities` should also store the entity type for the entity used as the key.

**Comment by ArrowRaider** [comment]
FYI, here is another case that causes the exception:
Using the code ajcvickers provided, change the Program class to the following:
`public class Program
    {
        public static async Task Main()
        {
            using (var context = new BloggingContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var owner = new Owner1 { Owned = new Composite() };
                context.Entry(owner).State = EntityState.Added;
                await context.SaveChangesAsync();
                context.Entry(owner).State = EntityState.Deleted;
                await context.SaveChangesAsync();
            }
        }
    }`

The exception will be thrown at the second `await context.SaveChangesAsync();` line.  Note that this exception is thrown after the data has been saved, so the row is in fact deleted in the database, and then it crashes during the detach phase.
