### ISSUE TITLE
[Perf] Micro-benchmarks broken

### ISSUE THREAD

**Issue by sebastienros** [aspnet/EntityFrameworkCore#17721]
Probably due to a recent update in required dependency versions, but the SDK that is set in `global.json` doesn't provide them. If I force a specific runtime to be installed then the benchmarks work again.

**Comment by sebastienros** [comment]
Branch release/3.0

**Comment by roji** [comment]
Can you post the specific error/problematic dependency etc.? Does it matter which runtime you force to get this to work?

BTW I see release/3.0 still uses preview8 as its SDK in global.json, shouldn't we be on preview9? /cc @bricelam

**Comment by bricelam** [comment]
@aspnet/build Should we bump the SDK?

**Comment by sebastienros** [comment]
What I don't understand if why you would have a bot automatically upgrading the references to external packages, but not the required SDK that would actually come with some of these. Or maybe these dependencies are included as part of another step in the build scripts?

**Comment by bricelam** [comment]
lol, I ask that question every time. I still feel like they didn't deliver https://github.com/dotnet/arcade/issues/811

**Comment by dougbu** [comment]
The preview 9 SDK comes with new NuGet MSBuild glue which causes new warnings all over the place. Fine to update the SDK but only in combination with required fixes e.g. move to embedded package icons (if possible) and not for 3.0 GA without ask-mode approval.

More generally, this is a topic for our leads because the embedded icons bit is somewhat ugly. Separately, adding dependencies for SDK versions creates a circular dependency loop which seems to scare people. The main mechanism at the moment is Arcade SDK updates that force a minimum version of the SDK.

**Comment by dougbu** [comment]
Should have said "new errors" because we have warnings-as-errors enabled.

**Comment by roji** [comment]
@sebastienros can we work around this by forcing the SDK for now, until EF Core switches to preview9/RTM?

**Comment by sebastienros** [comment]
The benchmarks can force it, and it's the default normally, but because this repos has a global.jsob that also forces it, I had to add an option to not do it actually. So a way would be for this branch to not have a global.json instead. Otherwise msbuild fails silently when provided two conflicting versions.

**Comment by roji** [comment]
I don't think removing the global.json is an option (for test CI/CD, for reliable builds locally), @bricelam?

As a super ugly hack, maybe remove global.json recursively if the option to force the SDK is specified?

**Comment by sebastienros** [comment]
The benchmarks are working again normally. Please confirm and close the issue.

**Comment by roji** [comment]
Yep, I can see results coming in, thanks!
