### ISSUE TITLE
DatabaseFacade.CanConnect throws instead of returning false

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#18355]
On SQL Server, if the database server is down, an SqlException is thrown instead of returning false. It seems like we should catch all exceptions internally and return false instead.

**Comment by roji** [comment]
@rynowak what would be the expected behavior here from the ASP.NET health check perspective? It seems problematic for this method to sometimes throw and sometimes return false - what do other health checks do?

**Comment by roji** [comment]
@rynowak ping

**Comment by ajcvickers** [comment]
@rynowak Pinging you now you've been right-side-up for a while. What is the general guidance on health checks and exceptions. Should any error report back as false, or should unexpected errors be surfaced as exceptions?

**Comment by rynowak** [comment]
I would expect it to return false 😁 

Health checks are an abstraction/isolation layer. A health check should return "Unhealthy" if the check fails, that's preferrable to an exception. If the check throws an exception that will be logged differently.

Since checks are are abstraction layer, it's also reasonable for a check to handle exceptions from whatever it's checking. Some of them do that because that's the only option. In the case that you want to have the exception convey something meaningful and log that too, it's an option. 

In general though returning false is preferrable to throwing.

**Comment by ajcvickers** [comment]
@rynowak Thanks!

**Comment by antoinecfmws** [comment]
Hello @roji , we are using EF Core Dbcontext 3.1.0, and the `dbContext.Database.CanConnect()` still throws an exception if the server is offline. I thought this was pushed to master. Thoughts?

**Comment by roji** [comment]
@antoinecfmws this was done too late for 3.1.0, so will be released for 5.0.0 (and its previews). This is why this issue is in the 5.0.0 milestone.

**Comment by antoinecfmws** [comment]
Makes sense now, thank you! Sorry to bother @roji
