### ISSUE TITLE
Query: Make OrderBy optional in RowNumber

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#19331]
See https://github.com/aspnet/EntityFrameworkCore/pull/19317

@roji - Is Partition By also optional or required?

Verify conditions here https://github.com/aspnet/EntityFrameworkCore/blob/5400c5bf76a5e7f3fc16197e04235819fc1bd998/src/EFCore.Relational/Query/SqlExpressions/RowNumberExpression.cs#L22-L23

**Comment by roji** [comment]
Will investigate tomorrow

**Comment by smitpatel** [comment]
Partition by is optional in t-sql

**Comment by smitpatel** [comment]
Removing from milestone.
Decided that partitions can be null, we would put empty list in ctor.
Even though Ordering is optional in SQL we should make it required in our code. RowNumberExpression essentially computes the row number for given record and for it to be deterministic, it has to have a deterministic order. `(SELECT 1)` in sql may look ugly but that is by design so that user knows they did not specify ordering.
We already have plan to log a warning for FirstOrDefault kind row limiting operations without order by.

**Comment by roji** [comment]
@smitpatel do you see any difference between `(SELECT 1)` in RowNumberExpression and `(SELECT 1)` in a regular SelectExpression OrderBy clause? I mean, users can ask for a random entry (or two entries) coming out of the window function, just like they can ask for a random Customer in a simple top-level query.

To be clear, if you're proposing to de-prioritize this because it's only a clean-SQL issue (and complex/annoying to implement), that's one thing. But I'm trying to understand why we'd do #19332 but not this.

> Decided that partitions can be null, we would put empty list in ctor.

That would mean the constructor parameter remains non-nullable, but can be empty, right? (just thinking ahead to nullability annotation etc.)
