### ISSUE TITLE
Invalid SQL query gets generated when checking for null in LINQ

### ISSUE THREAD

**Issue by mkxpo** [aspnet/EntityFrameworkCore#27609]
Invalid SQL query gets generated when checking for null in LINQ in a specific manner: `(<entity>.<field> == null ? "value" : <entity>.<field>) == "value"` in a Where clause.

Steps to reproduce
---------------------

```
CREATE TABLE _TEMP (
  Id INT,
  Data NVARCHAR(4000) NULL,
)
```
```csharp
var dbContext = new DataContext();

string sql = dbContext.Temps
     .Where(t => (t.Data == null ? "man" : t.Data) == "man")
     .ToQueryString();

Console.WriteLine(sql):
```

Expected result (SQL):
------------------------

```sql
SELECT [_].[Id], [_].[Data]
FROM [_TEMP] AS [_]
WHERE (CASE WHEN [_].[Data] IS NULL then N'man' ELSE [_].[Data] END) = 'man'
```

Actual result (SQL):
---------------------

```sql
SELECT [_].[Id], [_].[Data]
FROM [_TEMP] AS [_]
WHERE [_].[Data] IS NULL
```
                
Further technical details:
---------------------------

EF Core version: 6.0.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.3
Target framework: .NET 6.0

**Comment by maumar** [comment]
SqlExpressionSimplifyingExpressionVisitor is over-eager in it's optimization. Initially we generate

```sql
WHERE CASE
	WHEN m.Data == NULL THEN N'man'
	ELSE m.Data
END == N'man'
```

which is "simplified" to `m.Data == NULL` but this doesn't account for situation where the second condition also equals 'man'. 
We should optimize to WHERE m.Data == NULL OR m.Data = N'man' (i.e only remove the condition that has been matched, rather than the entire case block). We should probably do this optimization only when case has 2 elements, otherwise we create comparison and a slightly smaller case block which doesn't look much better

**Comment by smitpatel** [comment]
Add extra check that else result is not the same.
https://github.com/dotnet/efcore/blob/915000c0100415bc7d2d776c04472673cca2a8ab/src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs#L230-L234
