### ISSUE TITLE
What does the time in Cosmos EF log entries represent?

### ISSUE THREAD

**Issue by ghost** [aspnet/EntityFrameworkCore#28243]
What does the milliseconds time in Cosmos EF log entries such as the following represent:
`Executed ReplaceItem (3324.3821 ms, 20.57 RU)`
`Executed ReadNext (2211.3767 ms, 10.15 RU`

Presumably it is the whole time that EF takes for the operation and not just the Cosmos API roundtrip time?

I get much shorter times just making these calls directly in cosmos.azure.com so I assume its more than just the API roundtrip time.

**Comment by roji** [comment]
The times represent the full time to complete e.g. a ReadNext operation from the client, i.e. including network roundtrips from your .NET application to CosmosDB ([this method specifically](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.Azure.Cosmos.CosmosDiagnostics.GetClientElapsedTime?view=azure-dotnet&viewFallbackFrom=netstandard-2.0)). I'm guessing what you're seeing in cosmos.azure.com has no client->Cosmos networking.

**Comment by acrov** [comment]
I'm on a decent broadband connection (36MB, 11ms ping) so whilst some time will be obviously be network time there is no way that the 1-2second discrepancy is wholly networking.

The observed query time using cosmos.azure.com is less than half a second. The sum of all the network calls  in chrome dev tools during the query is around 100-200ms.

The document being queried has a large object array (622 items, each item has 2 numbers) so I'm wondering if these high elapsed times might be due to EF tracking each array item.

**Comment by roji** [comment]
@acrov I think so, but have you tried a non-tracking query?

More importantly, EF Core simply wraps the standard CosmosClient, and ReadNextAsync is nothing more than a thin wrapper around [FeedIterator.ReadNextAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.feediterator.readnextasync?view=azure-dotnet#microsoft-azure-cosmos-feediterator-readnextasync(system-threading-cancellationtoken)). It should be easy to write a quick Cosmos client app which doesn't use EF Core, and execute it on the same machine. That would isolate EF Core's runtime impact in an easy, clean way.
