### ISSUE TITLE
Enable options on CREATE DATABASE statements to SQL Azure

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFrameworkCore#2969]
Enable SQL Azure users to modify the pricing tier, size, and edition options issue with `CREATE DATABASE`.

Example: 

``` sql
CREATE DATABASE BroniesCloud
{
     MAXSIZE = 30 GB ;
     EDITION = 'standard' ;
     SERVICE_OBJECTIVE = 'S1' ;
}
```

**Comment by rowanmiller** [comment]
**EF Team Triage:** Agreed this would be good. We originally looked at moving the database creation to be an explicit API call in the first migration for this reason... but it ended up being so different from other migration operations that we abandoned that approach. We should look at making this a first class API (perhaps in OnConfiguring, or an overload of EnsureCreated and ApplyMigrations).

@natemcmaster moving to backlog but perhaps you will need to tackle this for the test work you are doing.

**Comment by ajcvickers** [comment]
We discussed this again in triage and decided to close for now because:
* EnsureCreated is intended for rapid prototyping and testing where SQL Azure is not usually used
  * Publishing and deployment scenarios will not normally use this mechanism to create the actual database
* EnsureCreated and Migrations can work with an already created empty database, which means that the desired database can be created in the portal and used with EF
* We no longer really need this for testing

As always, we will reconsider this with sufficient feedback, and we might consider a PR if it was well written and not intrusive on the normal experience.

**Comment by divega** [comment]
Tentatively assigned to 3.1, subject to approval.

**Comment by divega** [comment]
Related: https://github.com/aspnet/EntityFrameworkCore/issues/6577. If we add a mechanism in model builder to configure database creation options, we can cover aspects mentioned in that issue as well.

**Comment by divega** [comment]
This is approved for 3.1.
