### ISSUE TITLE
Query: Investigate query parameterization of non-translatable expressions involving context instances

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFrameworkCore#7222]
E.g.
```c#
context.Customers.Where(c => context.SomeClientMethod(c));
```
This is likely edge, and there are easy workaround, but I suspect we might leak here (via cache key).

**Comment by anpete** [comment]
We should investigate doing the parameterization thing we did for filters. I.e. always parameterize DbContext instances.

**Comment by smitpatel** [comment]
In 3.0 where cannot do client eval.
- Putting that in projection, we don't leak since context is parameterized as it is coming from closure.
- If context is inlined then we have new expression in the tree rather than instance itself so we initialize it for each result.
- If context is captured as constant then we throw memory leak exception.
