### ISSUE TITLE
Query: SelectMany subquery from a GroupJoin'ed subquery fails to compile

### ISSUE THREAD

**Issue by tuespetre** [aspnet/EntityFrameworkCore#7906]
Example test:

```
        [ConditionalFact]
        public virtual void GroupJoin_Subquery_with_Take_Then_SelectMany_Where()
        {
            AssertQuery<Customer, Order>(
                (cs, os) => from c in cs
                            join o in os.Take(100) on c.CustomerID equals o.CustomerID into lo
                            from o in lo.Where(x => x.CustomerID.StartsWith("A"))
                            select new { c.CustomerID, o.OrderID });
        }
```

It blows up when `SqlTranslatingExpressionVisitor` attempts to translate the `WhereClause` in the subquery of the `AdditionalFromClause`, because it can't find a matching table in the `SelectExpression` for the `MainFromClause` of the subquery.

**Comment by smitpatel** [comment]
The issue here is incorrect association of additional from clause with select expression. There is no defaultIfEmpty operator so we need to do groupjoin on client (even after joining queries using LOJ). When we visit the additional where clause which iterating the grouping, we associate the previous select expression with it. This further worsen the situation. Even though we have group join done on client, we still try to translate the where predicate to server (which is not possible). Even in the case of client eval of predicate, we still get the previous select expression and try to bind property to it causing error that the table is not found in select. The reason for table not found in select expression is wrong select expression associated with the query source.

Assigning to @maumar since this is in the area of groupjoin translation.
