### ISSUE TITLE
Support collections of owned entities

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#8172]

**Comment by SneezeWeeze** [comment]
Any chance this will be included in the 2.1.0 release in Q4?

**Comment by AndriySvyryd** [comment]
@SneezeWeeze It's currently in the Backlog, meaning it is not planned for the next release.
You can vote for features by using the +1 reaction on the original comment (👍)

**Comment by crhairr** [comment]
I don't think #246 should be considered closed without this since enumerables are a very common use case for complex types in the NoSQL world.

But I'd also like to add to this that key-value/dictionary types should be supported, as this is another very common "enumerable" complex type in the NoSQL world.

**Comment by divega** [comment]
> I don't think #246 should be considered closed

@crhairr it seems our team just tracks work very differently from what you expect. In case it helps you understand: 

- We often close issues when significant portions of the scenarios they originally represented are covered. Then we create new issue for remaining scenarios. As [I already explained to you](https://github.com/aspnet/EntityFrameworkCore/issues/246#issuecomment-343550173), #246 was closed because owned types can already do a superset of what complex types could do in EF6, and that was a very significant milestone for us. 
- Although dictionaries are somewhat related to this issue, they are tracked separately in #2919.

**Comment by crhairr** [comment]
Yeah, I saw the dictionary issue earlier and already upvoted it. I meant to come back here and reference it directly to link the two.

As for how you track your work: at every company I've ever been at that uses Agile, the dev team would have gotten yelled at for closing issues when "significant portions" were done, instead of when the issue was "completely done" according to original acceptance criteria. I guess that standard has been ingrained in me, and I'll be less combative on it. ;)

What I'm really interested in is better support for third-party, NoSQL DB providers for EFCore. Complex Type support is a huge part of that and seems like relatively low-hanging fruit given how rich EFCore's metadata system already is. Properly supporting complex types would go a very long way to getting more third party DB providers in play and having a more expanded EFCore community. It would also REALLY help me out with my MongoDB provider. ;)

**Comment by divega** [comment]
@crhairr regarding the important of these features for supporting document oriented databases, I think we are in complete agreement. 

@smitpatel is currently working on a provider for the Document DB API in Cosmos DB and we hope to learn a lot about what is missing and how to approach document databases in general. I would recommend that you track his steps in this process and that you keep engaging in conversations with us about this. Ideally, your expertise on the MongoDB requirements will help us produce a better design that can accommodate more document database providers easily.

**Comment by ahmedtolba1984** [comment]
@AndriySvyryd  @divega 
When will you support this feature '**Collection of Owned Types**' ?

**Comment by divega** [comment]
@ahmedtolba1984 the plan is to do work on this soon after we finish 2.1.

**Comment by ahmedtolba1984** [comment]
@divega 
Thanks :)

**Comment by xKloc** [comment]
This can't happen soon enough. My domain models will be so much cleaner.

**Comment by kjbetz** [comment]
@xKloc How are you doing this now? Are you using Value Objects/Owns One?

**Comment by andriysavin** [comment]
I'm just curious what are the ways to implement collections of owned types in relational DBs (besides naïve serialization to a single cell)? 
I'm also wondering (not criticizing), why is this needed at all. If the goal is to support collections of VALUE OBJECTS (DDD), this can easily and naturally (for relational DBs) be achieved with EF entities with shadow id (PK) properties,  which would be just mapped to a separate table.

**Comment by tuespetre** [comment]
@divega is implementing this going to help reach for M2M mapping?

**Comment by ajcvickers** [comment]
@tuespetre Not directly. It's more about aggregates support, which goes to handling documents, which goes to Cosmos DB. The main prerequisites for many-to-many are skip-level nav props and property bag entity types.

**Comment by tuespetre** [comment]
@ajcvickers ahhh Cosmos DB, I see now. Thanks

**Comment by ahmedtolba1984** [comment]
@AndriySvyryd  Thank you :)
