### ISSUE TITLE
Add Code Literal Generation to Type Mapping

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#8741]
Currently, all intrinsic types are handled by `ICSharpHelper` (or `ICSharpUtilities` for RevEng), and if we encounter a type we don't understand, we'll throw.

Instead of throwing, we should ask the provider if they know how to generate a literal for the type. We'll do this by adding a method similar to the following to `RelationalTypeMapping`.

```C#
string GenerateCodeLiteral(object value, string language)
```

`language` will probably be the file extension of the code file we're generating (e.g. `.cs` for C#).

If a value is returned, we'll use it. If `null` is returned we'll continue to error with unknown literal.

Optionally, we could move the existing literal generation code to the type mappings so that they become the source of truth for all literal generation.

If an application wanted to support literal generation for a new language (e.g. Visual Basic or F#), they could override the provider type mapping implementation to handle that language.

**Comment by divega** [comment]
@bricelam thanks for writing this down. Question: do you envision the `language` parameter also in the methods of the "built-in" literal generation code (i.e. what currently lives in `ICSharpHelp` and `ICSharpUtilities`)? Perhaps it is ok to punt altogether on the multi-language support, but it might be relevant since you are working on https://github.com/aspnet/EntityFramework/issues/1671.

**Comment by divega** [comment]
@bricelam I guess I am just being skeptical about the `language` parameter approach. Nothing to worry about in the short term.

**Comment by ajcvickers** [comment]
See also #12979.

Removing this from backlog to see if we want to do this in 3.0, where we may be able to break if it becomes necessary.
