### ISSUE TITLE
RevEng: AnnotationCodeGenerator API is possibly insufficient

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#9121]
With 2.0.0's new scaffolding design, I took a stab at scaffolding PostgreSQL extensions as suggested in https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/102 by @smitpatel. PostgreSQL extensions are modeled as annotations on the database model itself (as they're database-global entities).

Adding annotations to the model in my NpgsqlDatabaseModelFactory worked very nicely, so I went to the next step of trying to nicely render those annotations with NpgsqlAnnotationCodeGenerator, so that instead of `.HasAnnotation("Npgsql:PostgresExtension:pgcrypto", "'pgcrypto', '', ''")` we get the much nicer `HasPostgresExtension("pgcrypto")` - and ran into an issue.

They way I had it, `HasPostgresExtension()` returned an `NpgsqlPostgresExtensionBuilder` (a bit like a sequence builder) which allowed the user to specify version information for the extension. Since the scaffolding simply chains together the strings that NpgsqlAnnotationCodeGenerator returns, when I had more than one extension compilation failed, because the second `HasPostgresExtension()` was being called on the first one's output, which was an `NpgsqlPostgresExtensionBuilder` rather than a `ModelBuilder`.

Fortunately specifying versions when setting up PostgreSQL extensions is really rather rare, so I just removed `NpgsqlPostgresExtensionBuilder` altogether and now `HasPostgresExtension()` returns a `ModelBuilder` like other simple annotations. However, you may wish to consider expanding this API for similar cases where annotations model a more complex database entity, and a builder is absolutely required.

**Comment by smitpatel** [comment]
cc: @bricelam 
I looked at code in Snapshot generator too. The only place we make multiple lines for annotations is `ToTable` & discriminator for EntityType. Which we do special case. Sequences are generated differently. Apart from that we have always scaffolded annotations chained. Perhaps never encountered case where some different builder was being returned from provider.

Scaffolding provider specified annotation separately would result in potentially bad code. Like `HasKey` & `HasIndex` which specifies `IsClustered` would have 2 long lines. Or perhaps we can special case model level & entity type level annotations separate here since they have more probability to start a different builder chain. i.e. For every case where provider specify fluent api for model/entityType, we will scaffold it in separate line. For all the rest (EF Core/Relational annotations) and any other non-rendered annotations would be chained.

Thoughts?

**Comment by roji** [comment]
I'd avoid approaches which treat different things differently here (i.e. entity types vs. sequences vs. the entire model...).

One trivial way around this is to allow the annotation code generator to specify whether its result is chainable or not (e.g. via an out parameter). If a `GenerateFluentApi` return true, then you guys know to simply terminate the chain and start a new line with the same builder. Otherwise you continue chaining. You could even add default implementations for overloads with the isChainable flag which call the one without the flag, passing false - this would keep current code exactly as it is, while allowing for non-chainable providers.

**Comment by smitpatel** [comment]
It would be good to avoid treating things differently. A flag (or some indication) to indicate, terminate chain is good. The reason model/entity type are special because it is only 1 level of call which are easy to write and has `buildAction`
```C#
modelBuilder.Entity<A>(b => {
    b.Extension1();
    b.Extension2();
}
```
opposed to 
```C#
modelBuilder.Entity<A>(b => {
    b.Property(e => e.Prop).Extension1();
    b.Property(e => e.Prop).Extension2();
}
```
The later case becomes uglier due to larger repetition. We also explicitly made decision not to have `buildAction` lambda on second level. So in any case if provider is writing code on property which is non-chainable it would be a bad UX hence bad design. 

Regardless,
how important it is for Postgre to return non-chainable fluent API on any metadata? We are already done for code changes for 2.0 release. Bar to make a change at this stage would be bit higher.

**Comment by divega** [comment]
> One trivial way around this is to allow the annotation code generator to specify whether its result is chainable or not (e.g. via an out parameter)

@smitpatel @roji is this something that could be added later without it being a breaking change? If we believe the resulting API would be less than ideal and the capability is a common need then it may be easier to make the argument for making the change now.

**Comment by roji** [comment]
First, this is definitely not a request for 2.0 - don't worry about it. As I wrote above, the only reason I currently have for non-chainable fluent APIs is specifying versions on PostgreSQL extensions, which frankly nobody really needs. So at least for now I simply dropped that feature, and extensions are added as simple metadata and are chainable. If people complain in the future (which I doubt very much) we can revisit.

Regardless, definitely understood about the special case for EntityType - the most important thing is to generate good code here.

If you guys are OK with the idea of adding `isChainable` out param on `GenerateFluentApi`, this could be added without breaking anything as I proposed above, i.e. by providing default virtual implementations that simply call the current overloads (without the flag). I can submit a PR at some point for that.

**Comment by bricelam** [comment]
We could add a third method: `IsTerminating` instead of an out parameter.

**Comment by roji** [comment]
@bricelam you mean that EF Core would precede every call to a `GenerateFluentApi` method with another call to `IsTerminating`, to know whether that annotation produces chainable code or not? It seems possible, although you do lose the type of thing you're generating code for (model vs. entitytype vs. property...). It also means you have to write code which deals with the same annotation in two different places - once to say whether it's chainable or not, and another time to actual generate the C# code for it.

**Comment by bricelam** [comment]
Just brainstorming. I figured we could defer the code generation of any that are terminating. If we only end up with one, just tack it onto the end of the chain.

**Comment by roji** [comment]
Hmm... true, although you could also do that with the `isChainable` out var we proposed above, i.e. call all `GenerateFluentApi` methods and arrange their string outputs based on their `isChainable` outputs...

**Comment by bricelam** [comment]
In version 2.1, we switched from returning `string` to a more structured type. In the future, we can enhance this type with additional information about chained calls and whether the consumer can continue the original chain after applying this fragment.

Closing as resolved for now. We can file new issues as specific needs arise.
