### ISSUE TITLE
Customize constraint name generation on provider implementations

### ISSUE THREAD

**Issue by carlosga** [aspnet/EntityFrameworkCore#9209]
Hello:

¿ What would be the best way to customize the constraint name generation ( for foreign keys, indexes, etc... ) on providers targeting servers with a given limit for identifiers ?,  for example, if i'm not wrong, PostgreSQL has a  63 bytes limit for identifiers.

I'm giving a try using custom conventions to rename the constraint when the default generated name exceeds the specific limit, but maybe there is a better way to do it.

Thanks in advance.

**Comment by ajcvickers** [comment]
@carlosga I think we need a way for providers to easily hook into this, like we did for alias lengths in query. Leaving this issue open to track that.

For now, the workarounds we came up with are:
* Use a custom convention, as you said, but be aware that custom conventions are currently internal because the API hasn't been finalized yet. We may break them in a future release.
* Manually configure constraint names that are two long. For example:
```C#
modelBuilder.Entity<ApplicationUser>()
    .HasKey(e => e.Id)
    .HasName("MyShortConstraintName");
```
* Iterate over the model at the end of OnModelCreating and use your own name generator to change the constraint names. Something like:
```C#
foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
    foreach (var key in entityType.GetKeys())
    {
        key.Relational().Name = BuildMyConstraintName(key);
    }

    foreach (var foreignKey in entityType.GetForeignKeys())
    {
        foreignKey.Relational().Name = BuildMyConstraintName(foreignKey);
    }

    foreach (var index in entityType.GetIndexes())
    {
        index.Relational().Name = BuildMyConstraintName(entityType);
    }
}
```

**Comment by AndriySvyryd** [comment]
We could do this by adding default value providers - classes with a method the returns the needed value and implement the corresponding conventions to clear out the value when any input changes. Instances of these providers would be stored in well known annotations on the model by a model convention. A `ConfigurationSource` value of `Default` could be introduced to indicate that a value has been set.

Setting the value instead of falling back to calculating it when it hasn't been set would improve perf as we only calculate it once. Only invoking the default value provider when the value is requested improves perf by avoiding the calculation when it's not needed.

This should be applied to other calculated default that could be customized by providers such as `Property.ValueGenerated`
