### ISSUE TITLE
Rev engineering does not support case sensitivity when 2 tables are having same name but case is different

### ISSUE THREAD

**Issue by archanasoni** [aspnet/EntityFrameworkCore#9257]
Hi,

We're working to have support for Design Tooling for IBM EF Core provider. 
We have come across a situation where DB2 Database is having 2 table for example
1. TestTable
2. TESTTABLE
Note: DB2 support this scenario and treats as different object.

When we try to create model via tooling model gets generated But in generated model only one POCO class exist. Context class is having correct entry.

Generated POCO file is having name as TestTable.cs but class name is Testtable

This could be the reason as for windows both are same so it's overriding class info of TestTable.cs.

We can see diff for SQL Server and DB2 in DatabaseModelFactory.cs is:
_tableColumns = new Dictionary<string, ColumnModel>(StringComparer.OrdinalIgnoreCase);
where as for DB2 we have:
_tableColumns = new Dictionary<string, ColumnModel>);

Also we looked for POCO .cs file generator in StringBuilderCoreWriter.cs
And here we are using Display name, which is having correct value if we look from DB2 perspective But for this logic will treat same file for both the table:
  foreach (var entityConfig in modelConfiguration.EntityConfigurations)
            {
                generatedCode = EntityTypeWriter.WriteCode(entityConfig);

                // output EntityType poco .cs file
                var entityTypeFileName = entityConfig.EntityType.DisplayName() + FileExtension;
                var entityTypeFileFullPath = FileService.OutputFile(
                    outputPath, entityTypeFileName, generatedCode);
                resultingFiles.EntityTypeFiles.Add(entityTypeFileFullPath);
            }
 
If we test same scenario in EF5 it works perfectly and generating EntitySet:
1.TestTable
2.TESTABLE1

**Comment by archanasoni** [comment]
Another observation is if 1 table name is in caps and 1 in small 
1. TESTTABLE
2. testtable

it works, combination with mixed case and upper or lower table name is having issue.

**Comment by smitpatel** [comment]
@archanasoni - Which version of EF Core are you depending on?

**Comment by archanasoni** [comment]
@smitpatel , currently we are dependent on EF Core 1.1.1 version.

**Comment by smitpatel** [comment]
I have looked at the code and implementation. There are many mismatches in string comparison which causes this issue.

- Providers creates `DatabaseModel` so it can have tables with same name (different casing).
- When we generate EntityType name by pascal casing the database table name and unique-fying it. This bit does case sensitive comparison.
- The file name is decided based on the Entity Type name so they are case sensitive but in windows system file names are case insensitive so we overwrite the same file.

For scenario 1 above:
`TestTable` becomes `TestTable` (preserving pascal casing)
`TESTTABLE` becomes `Testtable` (converting to pascal case)
They are different strings but ends up in same file causing issue.

For scenario 2 above:
`TESTTABLE` & `testtable` both become `Testtable` after pascal casing. So they get unique-fied and generated different names.

Action item:
We need to decide if our entity type display names are unique case insensitive or not because above example fails in windows but would work in Linux.
Based on that we can determine the default comparison in our entity type namer to fix the issue.

@archanasoni - We will be certainly fixing this in 2.1.0 release of EF. This will still remain issue in 1.1.2 & 2.0.0 packages (which are yet to be released). But to fix in those releases we need to put it in a patch. And it may not be cross the bar for patch.

**Comment by divega** [comment]
*EF Triage*: this feels like a corner case but we think we can simply make the logic that produces unique names case insensitive, i.e. produce two different class names for this case that differ on more than just the casing.
