### ISSUE TITLE
Benchmarks: Run with SQLite provider

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#9681]
This will help us detect any regressions in both Microsoft.EntityFrameworkCore.Sqlite and Microsoft.Data.Sqlite.

(For both 2.0.0 and dev)

**Comment by smitpatel** [comment]
See https://github.com/aspnet/EntityFrameworkCore/pull/9177#issuecomment-315282385

It was ask from provider writers to generate a set of test (like our specs tests), so that any provider can run benchmark tests against those.

We can either do the simplest here and copy code to run against SQLite or
We can refactor the code.
