### ISSUE TITLE
Projecting out bool value from ternary expression throws

### ISSUE THREAD

**Issue by rousselleg** [aspnet/EntityFrameworkCore#9818]
OneToZeroOrOne relationships do not let you check for null and provide values back in the EF query. 
 Instead you need to return the entire object from the database and then inspect the properties you are concerned about.

I also published this question to https://github.com/aspnet/EntityFrameworkCore/issues/6177 before I realized it was closed.

This code fails :
``await _repo 
   .TableNoTracking 
   .Where(x => x.Username == profileName) 
   .Select(x => new { IsAdmin = x.User != null ? x.User.IsAdmin : false }) 
   .FirstOrDefaultAsync()``

This code works fine, but we are forced to return the entire object.
`await _repo .TableNoTracking 
   .Where(x => x.Username == profileName) 
   .Select(x => new { User = x.User }) 
   .FirstOrDefaultAsync()`

### Further technical details
EF Core version: 2.0.0
Operating system: Windows 8.1
IDE: 
Microsoft Visual Studio Enterprise 2017 
Version 15.3.4
VisualStudio.15.Release/15.3.4+26730.15
Microsoft .NET Framework
Version 4.7.02053

**Comment by ajcvickers** [comment]
@rousselleg This is probably due to the FK being non-nullable, and would therefore be by-design as described in #6177. However, if you think this is a different case than #6177, then can you please post a complete code listing or project that reproduces what you are seeing so we can investigate further.

**Comment by smitpatel** [comment]
@rousselleg - I am not sure if you are hitting the same issue but I did uncover one bug while trying to reproduce this.
This query works fine. i.e. You can check for null and provide values back in EF query. (You don't need to check for null either because navigation access inside EF query is null-safe)
```C#
var query = db.Blogs.Where(b => b.Id == 1).Select(b => new
{
    Title = b.BlogDetails != null ? b.BlogDetails.Title : ""
}).FirstOrDefault();
```
But this query fails. Note the property being selected in ternary is bool type.
```C#
var query = db.Blogs.Where(b => b.Id == 1).Select(b => new
{
    IsTrue = b.BlogDetails != null ? b.BlogDetails.IsTrue : false
}).FirstOrDefault();

// SQL Generated
      SELECT TOP(1) CASE
          WHEN [b.BlogDetails].[Id] IS NOT NULL
          THEN [b.BlogDetails].[IsTrue] ELSE 0
      END AS [IsTrue]
      FROM [Blogs] AS [b]
      LEFT JOIN [BlogDetails] AS [b.BlogDetails] ON [b].[Id] = [b.BlogDetails].[BlogId]
      WHERE [b].[Id] = 1
```
When SqlServer applies case block with `0` in it, it will upcast the result to integer. So database column returns an int which we try to save in bool property hence it fails with following exception.
```
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Boolean'.
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
```

Perhaps we need to handle casting of bool returned column more accurately.
