### ISSUE TITLE
Incrorrect EntityState in ChangeTracker when assigning RowVersion directly

### ISSUE THREAD

**Issue by ManuelHaas** [aspnet/EntityFrameworkCore#9856]
When assigning the RowVersion property by using the setter method of the OriginalValue property the state of the database entity changes from 'Unchanged' to 'Modified' even if the RowVersion property has not been changed.
`var entryVersion = db.Entry(dbEntry).Property(u => u.RowVersion);`
`entryVersion.OriginalValue = data.RowVersion;`

In the above example the state of dbEntry always changes to 'Modified' even if the assigned RowVersion property holds the same byte value.

Am I doing something wrong? Is there another way of checking for concurrency that would be suggested instead of the above or is this a bug?

EF Core version: 2.0.0
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (Visual Studio 2017 (15.3.5))

**Comment by ajcvickers** [comment]
@ManuelHaas I haven't investigated this yet, but thinking about the code I can see how this might happen. However, it seems like it shouldn't make any difference since the the modified value should be ignored by the update pipeline anyway. Can you elaborate a bit on what behavioral issues this is causing so we can try to make a good assessment of the severity of the issue?

**Comment by ManuelHaas** [comment]
@ajcvickers You are right the database entity will be ignored by the pipeline. But I have overwritten the SaveChanges method to update a LastModifiedOn and a LastModifiedBy for entities that have EntityState Modified.

**Comment by ajcvickers** [comment]
@ManuelHaas Thanks for the additional info.
